# Generated by Django 4.2.2 on 2023-06-30 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_location_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardealer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.location'),
        ),
    ]
