# Generated by Django 4.2.2 on 2023-07-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_cardealer_car_dealer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tracking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.IntegerField(default=0)),
                ("timestamp", models.FloatField(default=0.0)),
                ("lat", models.FloatField(default=0.0)),
                ("lon", models.FloatField(default=0.0)),
                ("speed", models.FloatField(default=0.0)),
                ("bearing", models.FloatField(default=0.0)),
                ("altitude", models.FloatField(default=0.0)),
                ("accuracy", models.FloatField(default=0.0)),
                ("batt", models.FloatField(default=0.0)),
                ("charge", models.FloatField(default=True)),
            ],
        ),
    ]
