# Generated by Django 4.2.2 on 2023-07-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_tracking_charge_alter_tracking_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tracking',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
