# Generated by Django 4.2.2 on 2023-07-21 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_tracking_charge_alter_tracking_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tracking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.tracking'),
        ),
    ]
