# Generated by Django 4.2.2 on 2023-07-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_car_tracking_car_vehicle_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="vehicle_number",
            field=models.CharField(default=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.CharField(max_length=200),
        ),
    ]
