# Generated by Django 4.2.2 on 2023-07-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_car_tracking_car_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='start_time',
            field=models.IntegerField(default=0),
        ),
    ]
