# Generated by Django 4.2.2 on 2023-07-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_car_vehicle_number'),
    ]

    operations = [

    ]
