# Generated by Django 4.2.2 on 2023-07-31 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_car_vehicle_number_alter_car_image"),
        ("home", "0017_car_vehicle_number"),
    ]

    operations = []
