# Generated by Django 4.2.2 on 2023-08-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_order_order_id_order_status_alter_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vehicle_number',
            field=models.CharField(default=True, max_length=15),
        ),
    ]
