# Generated by Django 4.2.2 on 2023-08-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='payment_id',
        ),
    ]
