# Generated by Django 4.2.2 on 2023-08-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
