# Generated by Django 4.2.2 on 2023-08-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_order_end_date_order_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
