# Generated by Django 4.2.2 on 2023-08-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_order_end_date_remove_order_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=10),
        ),
    ]
