# Generated by Django 4.2.2 on 2023-08-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_merge_20230731_0626"),
        ("home", "0027_order_fuel_type"),
    ]

    operations = []
